apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pulseboard.fullname" . }}-prometheus-config
  labels:
    {{- include "pulseboard.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeIntervalSeconds }}s
      evaluation_interval: {{ .Values.prometheus.scrapeIntervalSeconds }}s
    scrape_configs:
      - job_name: pulseboard
        static_configs:
          - targets: ["{{ include "pulseboard.fullname" . }}:8000"]
