apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pulseboard.fullname" . }}-prometheus-data
  labels:
    {{- include "pulseboard.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- with .Values.prometheus.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.prometheus.persistence.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pulseboard.fullname" . }}-prometheus
  labels:
    {{- include "pulseboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "pulseboard.selector" . | nindent 6 }}
      app.kubernetes.io/component: prometheus
  template:
    metadata:
      labels:
        {{- include "pulseboard.selector" . | nindent 8 }}
        app.kubernetes.io/component: prometheus
      annotations:
        # Roll the pod when the scrape config changes.
        checksum/config: {{ include (print $.Template.BasePath "/prometheus-config.yaml") . | sha256sum }}
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --storage.tsdb.retention.time={{ .Values.prometheus.retention }}
          ports:
            - name: http
              containerPort: 9090
          readinessProbe:
            httpGet: { path: /-/ready, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /-/healthy, port: http }
            initialDelaySeconds: 15
            periodSeconds: 30
          resources:
            {{- toYaml .Values.prometheus.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
              readOnly: true
            - name: data
              mountPath: /prometheus
      volumes:
        - name: config
          configMap:
            name: {{ include "pulseboard.fullname" . }}-prometheus-config
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "pulseboard.fullname" . }}-prometheus-data
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulseboard.fullname" . }}-prometheus
  labels:
    {{- include "pulseboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: ClusterIP
  selector:
    {{- include "pulseboard.selector" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: http
